/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TokenGenerator;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Khizi
 */
public class TokenGeneratorGUI extends javax.swing.JFrame {
    PrinterService printerService;
    /**
     * Creates new form TokenGeneratorGUI
     */
    public TokenGeneratorGUI() {
        initComponents();
        printerService = new PrinterService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chawla Clinic Token Generator");
        setPreferredSize(new java.awt.Dimension(875, 700));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tokens Generated"));
        jPanel1.setPreferredSize(new java.awt.Dimension(718, 87));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("MALE");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("CHILD");

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextPane1.setText("##");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextPane2.setText("##");
        jScrollPane2.setViewportView(jTextPane2);

        jTextPane3.setEditable(false);
        jTextPane3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextPane3.setText("##");
        jScrollPane3.setViewportView(jTextPane3);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("FEMALE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generate Token"));
        jPanel2.setPreferredSize(new java.awt.Dimension(711, 137));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Patient's Name");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("MALE");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("FEMALE");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 255));
        jButton3.setText("CHILD");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton1)
                .addGap(66, 66, 66)
                .addComponent(jButton2)
                .addGap(64, 64, 64)
                .addComponent(jButton3)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Generated Tokens Logs"));
        jPanel4.setPreferredSize(new java.awt.Dimension(765, 374));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MALE");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FEMALE");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CHILD");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane6.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6))
                .addGap(27, 27, 27))
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Restore Backup?");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("RESTORE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("RESET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(33, 33, 33)
                        .addComponent(jButton5)
                        .addGap(162, 162, 162)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jLabel8))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String lineString = jTextField1.getText();
        if(lineString.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter TEXT First!");
        }
        else
        {
            int AntiCharFlag=0;
            for (int i = 0; i < lineString.length(); i++) {
                if(!(lineString.charAt(i)==' ' || (lineString.charAt(i)>='A' && lineString.charAt(i)<='Z') || (lineString.charAt(i)>='a' && lineString.charAt(i)<='z')))
                {
                    AntiCharFlag=1;
                }
            }
            if(AntiCharFlag==1)
            {
                JOptionPane.showMessageDialog(null, "Name cannot contain Numbers or Symbols!");
                jTextField1.setText("");
            }
            else
            {
                int num = Integer.parseInt(jTextPane1.getText());
                num++;
                jTextPane1.setText(String.valueOf(num));
                PrintToken("MALE", jTextPane1.getText());
                UpdateLogs("MALE", jTextPane1.getText());
                jTextField1.setText("");
                String OldString, NewString;
                OldString=jTextArea1.getText();
                if(OldString.equals(""))
                {
                    NewString=String.valueOf(num)+" - "+lineString+"\n";
                }
                else
                {
                    NewString=OldString+String.valueOf(num)+" - "+lineString+"\n";
                }
                WriteToFile("MData.bin", String.valueOf(num), NewString);
                jTextArea1.setText(NewString);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String lineString = jTextField1.getText();
        if(lineString.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter TEXT First!");
        }
        else
        {
            int AntiCharFlag=0;
            for (int i = 0; i < lineString.length(); i++) {
                if(!(lineString.charAt(i)==' ' || (lineString.charAt(i)>='A' && lineString.charAt(i)<='Z') || (lineString.charAt(i)>='a' && lineString.charAt(i)<='z')))
                {
                    AntiCharFlag=1;
                }
            }
            if(AntiCharFlag==1)
            {
                JOptionPane.showMessageDialog(null, "Name cannot contain Numbers or Symbols!");
                jTextField1.setText("");
            }
            else
            {
                int num = Integer.parseInt(jTextPane2.getText());
                num++;
                jTextPane2.setText(String.valueOf(num));
                PrintToken("FEMALE", jTextPane2.getText());
                UpdateLogs("FEMALE", jTextPane2.getText());
                jTextField1.setText("");
                String OldString, NewString;
                OldString=jTextArea2.getText();
                if(OldString.equals(""))
                {
                    NewString=String.valueOf(num)+" - "+lineString+"\n";
                }
                else
                {
                    NewString=OldString+String.valueOf(num)+" - "+lineString+"\n";
                }
                WriteToFile("FData.bin", String.valueOf(num), NewString);
                jTextArea2.setText(NewString);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String lineString = jTextField1.getText();
        if(lineString.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter TEXT First!");
        }
        else
        {
            int AntiCharFlag=0;
            for (int i = 0; i < lineString.length(); i++) {
                if(!(lineString.charAt(i)==' ' || (lineString.charAt(i)>='A' && lineString.charAt(i)<='Z') || (lineString.charAt(i)>='a' && lineString.charAt(i)<='z')))
                {
                    AntiCharFlag=1;
                }
            }
            if(AntiCharFlag==1)
            {
                JOptionPane.showMessageDialog(null, "Name cannot contain Numbers or Symbols!");
                jTextField1.setText("");
            }
            else
            {
                int num = Integer.parseInt(jTextPane3.getText());
                num++;
                jTextPane3.setText(String.valueOf(num));
                PrintToken("CHILD", jTextPane3.getText());
                UpdateLogs("CHILD", jTextPane2.getText());
                jTextField1.setText("");
                String OldString, NewString;
                OldString=jTextArea3.getText();
                if(OldString.equals(""))
                {
                    NewString=String.valueOf(num)+" - "+lineString+"\n";
                }
                else
                {
                    NewString=OldString+String.valueOf(num)+" - "+lineString+"\n";
                }
                WriteToFile("CData.bin", String.valueOf(num), NewString);
                jTextArea3.setText(NewString);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        GetFileData();
        jTextField1.setEditable(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jLabel8.setForeground(Color.GRAY);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextPane1.setText(("0"));
        jTextPane2.setText(("0"));
        jTextPane3.setText(("0"));
        jTextField1.setEditable(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jLabel8.setForeground(Color.GRAY);
    }//GEN-LAST:event_jButton5ActionPerformed
    private void WriteToFile(String FileName, String TokenCount, String FileData)
    {
        try {
            FileWriter myWriter = new FileWriter(FileName);
            myWriter.write(TokenCount+"\n"+FileData);
            myWriter.close();
        } catch(IOException e) {
            //System.out.println("An error occured");
            char FileCode = FileName.charAt(0);
            JOptionPane.showMessageDialog(null, "An Error occured writing to File (Code" + FileCode + ") , Please Contact Administrator.");
        }
    }
    private String GetSystemTime()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("hh:mm a, dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String TimeDateString = dtf.format(now);
        return TimeDateString;
    }
    private void PrintToken(String PatientType, String TokenNumber)
    {
        String TimeDateString = GetSystemTime();
        byte[] justify1 = new byte[] { 0x1b, 0x61, 49};
        byte[] fSize1 = new byte[] { 0x1d, '!', 35 };
        byte[] fSize2 = new byte[]{ 0x1d, '!', 17 };
        byte[] fSize4 = new byte[] { 0x1d, '!', 51 };
        byte[] fSize5 = new byte[] { 0x1d, '!', 0 };
        byte[] cutP = new byte[] { 0x1d, 'V', 1 };
        String justify1Str = new String(justify1);
        String fSize1Str = new String(fSize1);
        String fSize2Str = new String(fSize2);
        String fSize4Str = new String(fSize4);
        String fSize5Str = new String(fSize5);
        String cutPStr = new String(cutP);
        String ChawlaClinicName = "CHAWLA CLINIC";
        String TimeDate_PTypeToken = "\n" + TimeDateString + "\n" + "________________________\n\n" + PatientType + " TOKEN NUMBER\n";
        String HorizontalLine = "________________________\n\n";
        String Footer = "\n\n\n\n\n\nSOFTWARE DEVELOPED BY KHIZIR FARRUKH\nEMAIL: khizirfarrukh@outlook.com\n\n\n\n\n";
        String FullString = justify1Str + fSize1Str + ChawlaClinicName + fSize2Str + TimeDate_PTypeToken + HorizontalLine + fSize4Str + TokenNumber + fSize5Str + Footer + cutPStr;
        printerService.printString("BCPrinter", FullString);
//        String tempStr = new String(cutP);
//        int lastChar = (int) tempStr.charAt(tempStr.length() - 1);
//        System.out.println(new String(justify1));
//        printerService.printBytes("BCPrinter", justify1);
//        printerService.printBytes("BCPrinter", fSize1);
//        printerService.printString("BCPrinter", "CHAWLA CLINIC\n");
//        printerService.printBytes("BCPrinter", fSize2);
//        printerService.printString("BCPrinter", "\n" + TimeDateString + "\n" + "________________________\n\n" + PatientType + " TOKEN NUMBER\n");
//        printerService.printBytes("BCPrinter", fSize2);
//        printerService.printString("BCPrinter", "________________________\n\n");
//        printerService.printBytes("BCPrinter", fSize4);
//        printerService.printString("BCPrinter", TokenNumber);
//        printerService.printBytes("BCPrinter", fSize5);
//        printerService.printString("BCPrinter", "\n\n\n\n\n\nSOFTWARE DEVELOPED BY KHIZIR FARRUKH\nEMAIL: khizirkfc@gmail.com\n\n\n\n\n");
//        printerService.printBytes("BCPrinter", cutP);
    }
    private void GetFileData()
    {
        try{
            File MaleData = new File("MData.bin");
            Scanner myReader = new Scanner(MaleData);
            String TokenCount = myReader.nextLine();
            String TextAreaData = "";
            while(myReader.hasNextLine())
            {
                TextAreaData = TextAreaData + myReader.nextLine() + "\n";
            }
            jTextPane1.setText(TokenCount);
            jTextArea1.setText(TextAreaData);
        } catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Error 404: File (Code M) Not Found.");
            jTextPane1.setText("0");
        }
        try{
            File FemaleData = new File("FData.bin");
            Scanner myReader = new Scanner(FemaleData);
            String TokenCount = myReader.nextLine();
            String TextAreaData = "";
            while(myReader.hasNextLine())
            {
                TextAreaData = TextAreaData + myReader.nextLine() + "\n";
            }
            jTextPane2.setText(TokenCount);
            jTextArea2.setText(TextAreaData);
        } catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Error 404: File (Code F) Not Found.");
            jTextPane2.setText("0");
        }
        try{
            File ChildData = new File("CData.bin");
            Scanner myReader = new Scanner(ChildData);
            String TokenCount = myReader.nextLine();
            String TextAreaData = "";
            while(myReader.hasNextLine())
            {
                TextAreaData = TextAreaData + myReader.nextLine() + "\n";
            }
            jTextPane3.setText(TokenCount);
            jTextArea3.setText(TextAreaData);
        } catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Error 404: File (Code C) Not Found.");
            jTextPane3.setText("0");
        }
    }
    private void UpdateLogs(String PatientType, String TokenNum){
        String Date_Time = GetSystemTime();
        try {
            File f1 = new File("TokenLogs.txt");
            if(!f1.exists()) {
            f1.createNewFile();
        }
            FileWriter fileWritter = new FileWriter(f1.getName(),true);
            BufferedWriter bw = new BufferedWriter(fileWritter);
            bw.write("Patient Name: " + jTextField1.getText() + "\n");
            bw.write("Patient Type: " + PatientType + "\n");
            bw.write("Token Number: " + TokenNum + "\n");
            bw.write("Date/Time: " + Date_Time + "\n");
            bw.write("**************************************************\n");
            bw.close();
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error Updating Logs.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokenGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokenGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokenGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokenGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokenGeneratorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
